(define (let? exp) (tagged-list? exp 'let))
(define (let-bindings exp) (cadr exp))
(define (let->lambda exp)
  (define (let-variables exp) (map car (cadr exp)))
  (define (let-values exp) (map cdr (cadr exp)))
  (define (let-body) (cddr exp))
  ((make-lambda (let-variables exp) (let-body exp))
   (let-values exp)))
(define (make-let bindings body)
  (cons 'let (cons bindings body)))
